# syntax=docker.io/docker/dockerfile:1.18.0-labs@sha256:79cdc14e1c220efb546ad14a8ebc816e3277cd72d27195ced5bebdd226dd1025
# TODO: https://github.com/containers/buildah/issues/4211

# @help: https://docs.docker.com/reference/dockerfile
# @help: https://github.com/containers/common/blob/main/docs/Containerfile.5.md

# @see: https://hub.docker.com/_/ubuntu/tags
FROM --platform=${BUILDPLATFORM} docker.io/library/ubuntu:25.10@sha256:a61c057b4f69200ecf031519a20db79b8683837ba1dc2a59458d333eb75b174d AS base

RUN \
    --mount=type=bind,source=./features/src/common-utils/,target=/features/src/common-utils/ \
    --mount=type=cache,target=/var/cache/apt/,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/,sharing=locked \
    sh "/features/src/common-utils/install.sh"

FROM base AS feature-node

# @see: https://nodejs.org/en/download/archive/current
ARG VERSION="v24.9.0"

ENV NODE_PATH="/usr/local/lib/node_modules"
ENV NPM_CONFIG_CACHE="/root/.npm/"
ENV PATH="/opt/node/bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/node/,target=/features/src/node/ \
    --mount=type=cache,target=/tmp/node/,sharing=locked \
    sh "/features/src/node/install.sh"

FROM base AS feature-bash-language-server

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/usr/local/lib/node_modules"
ENV NPM_CONFIG_CACHE="/root/.npm/"
ENV PATH="/opt/node/bin:${PATH}"
COPY --from=feature-node --link "/opt/node/" "/opt/node/"
RUN \
    --mount=type=bind,source=./features/src/node/,target=/features/src/node/ \
    --mount=type=cache,target=/tmp/node/,sharing=locked \
    sh "/features/src/node/configure.sh"

# @see: https://npmjs.com/package/bash-language-server?activeTab=versions
ARG VERSION="5.6.0"

ENV NODE_PATH="/opt/bash-language-server/node_modules:${NODE_PATH}"
ENV PATH="/opt/bash-language-server/node_modules/.bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/bash-language-server/,target=/features/src/bash-language-server/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/bash-language-server/install.sh"

FROM base AS feature-docker-language-server

# @see: https://github.com/docker/docker-language-server/releases
ARG VERSION="v0.18.0"

ENV PATH="/opt/docker-language-server/bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/docker-language-server/,target=/features/src/docker-language-server/ \
    --mount=type=cache,target=/tmp/docker-language-server/,sharing=locked \
    sh "/features/src/docker-language-server/install.sh"

FROM base AS feature-dockerfile-language-server

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/usr/local/lib/node_modules"
ENV NPM_CONFIG_CACHE="/root/.npm/"
ENV PATH="/opt/node/bin:${PATH}"
COPY --from=feature-node --link "/opt/node/" "/opt/node/"
RUN \
    --mount=type=bind,source=./features/src/node/,target=/features/src/node/ \
    --mount=type=cache,target=/tmp/node/,sharing=locked \
    sh "/features/src/node/configure.sh"

# @see: https://npmjs.com/package/dockerfile-language-server-nodejs?activeTab=versions
ARG VERSION="0.14.1"

ENV NODE_PATH="/opt/dockerfile-language-server/node_modules:${NODE_PATH}"
ENV PATH="/opt/dockerfile-language-server/node_modules/.bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/dockerfile-language-server/,target=/features/src/dockerfile-language-server/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/dockerfile-language-server/install.sh"

FROM base AS feature-editorconfig

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/usr/local/lib/node_modules"
ENV NPM_CONFIG_CACHE="/root/.npm/"
ENV PATH="/opt/node/bin:${PATH}"
COPY --from=feature-node --link "/opt/node/" "/opt/node/"
RUN \
    --mount=type=bind,source=./features/src/node/,target=/features/src/node/ \
    --mount=type=cache,target=/tmp/node/,sharing=locked \
    sh "/features/src/node/configure.sh"

# @see: https://npmjs.com/package/editorconfig?activeTab=versions
ARG VERSION="3.0.1"

ENV NODE_PATH="/opt/editorconfig/node_modules:${NODE_PATH}"
ENV PATH="/opt/editorconfig/node_modules/.bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/editorconfig/,target=/features/src/editorconfig/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/editorconfig/install.sh"

FROM base AS feature-markdown-oxide

# @see: https://github.com/Feel-ix-343/markdown-oxide/releases
ARG VERSION="v0.25.8"

ENV PATH="/opt/markdown-oxide/bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/markdown-oxide/,target=/features/src/markdown-oxide/ \
    --mount=type=cache,target=/tmp/markdown-oxide/,sharing=locked \
    sh "/features/src/markdown-oxide/install.sh"

FROM base AS feature-prettier

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/usr/local/lib/node_modules"
ENV NPM_CONFIG_CACHE="/root/.npm/"
ENV PATH="/opt/node/bin:${PATH}"
COPY --from=feature-node --link "/opt/node/" "/opt/node/"
RUN \
    --mount=type=bind,source=./features/src/node/,target=/features/src/node/ \
    --mount=type=cache,target=/tmp/node/,sharing=locked \
    sh "/features/src/node/configure.sh"

# @see: https://npmjs.com/package/prettier?activeTab=versions
ARG VERSION="3.6.2"

ENV NODE_PATH="/opt/prettier/node_modules:${NODE_PATH}"
ENV PATH="/opt/prettier/node_modules/.bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/prettier/,target=/features/src/prettier/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/prettier/install.sh"

FROM base AS feature-rust

# @see: https://github.com/rust-lang/rustup/tags
ARG VERSION="1.28.2"

ENV CARGO_HOME="/opt/rust/cargo/"
ENV PATH="/opt/rust/cargo/bin:${PATH}"
ENV RUSTUP_HOME="/opt/rust/rustup/"

RUN \
    --mount=type=bind,source=./features/src/rust/,target=/features/src/rust/ \
    --mount=type=cache,target=/tmp/rust/,sharing=locked \
    sh "/features/src/rust/install.sh"

FROM base AS feature-shellcheck

# @see: https://github.com/koalaman/shellcheck/releases
ARG VERSION="v0.11.0"

ENV PATH="/opt/shellcheck/bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/shellcheck/,target=/features/src/shellcheck/ \
    --mount=type=cache,target=/tmp/shellcheck/,sharing=locked \
    sh "/features/src/shellcheck/install.sh"

FROM base AS feature-shfmt

# @see: https://github.com/mvdan/sh/releases
ARG VERSION="v3.12.0"

ENV PATH="/opt/shfmt/bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/shfmt/,target=/features/src/shfmt/ \
    --mount=type=cache,target=/tmp/shfmt/,sharing=locked \
    sh "/features/src/shfmt/install.sh"

FROM base AS feature-taplo

# @see: https://github.com/tamasfe/taplo/releases
ARG VERSION="0.10.0"

ENV PATH="/opt/taplo/bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/taplo/,target=/features/src/taplo/ \
    --mount=type=cache,target=/tmp/taplo/,sharing=locked \
    sh "/features/src/taplo/install.sh"

FROM base AS feature-zig

# @see: https://ziglang.org/download
ARG VERSION="0.15.1"
ARG ZSF_PUBLIC_KEY="RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U"

ENV PATH="/opt/zig/local/bin:/opt/zig/bin:${PATH}"

RUN \
    --mount=type=bind,source=./features/src/zig/,target=/features/src/zig/ \
    --mount=type=cache,target=/tmp/zig/,sharing=locked \
    sh "/features/src/zig/install.sh"

# @see: https://mcr.microsoft.com/artifact/mar/devcontainers/base/tags
FROM mcr.microsoft.com/devcontainers/base:2.0.4-ubuntu-24.04@sha256:ad92cae7c25cafb1e7bb5aa7520b81be85fac022ea92e404b94a11127631fae3 AS devcontainer

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/usr/local/lib/node_modules"
ENV NPM_CONFIG_CACHE="/root/.npm/"
ENV PATH="/opt/node/bin:${PATH}"
COPY --from=feature-node --link "/opt/node/" "/opt/node/"
RUN \
    --mount=type=bind,source=./features/src/node/,target=/features/src/node/ \
    --mount=type=cache,target=/tmp/node/,sharing=locked \
    sh "/features/src/node/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/opt/bash-language-server/node_modules:${NODE_PATH}"
ENV PATH="/opt/bash-language-server/node_modules/.bin:${PATH}"
COPY --from=feature-bash-language-server --link "/opt/bash-language-server/" "/opt/bash-language-server/"
RUN \
    --mount=type=bind,source=./features/src/bash-language-server/,target=/features/src/bash-language-server/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/bash-language-server/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV PATH="/opt/docker-language-server/bin:${PATH}"
COPY --from=feature-docker-language-server --link "/opt/docker-language-server/" "/opt/docker-language-server/"
RUN \
    --mount=type=bind,source=./features/src/docker-language-server/,target=/features/src/docker-language-server/ \
    --mount=type=cache,target=/tmp/docker-language-server/,sharing=locked \
    sh "/features/src/docker-language-server/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/opt/dockerfile-language-server/node_modules:${NODE_PATH}"
ENV PATH="/opt/dockerfile-language-server/node_modules/.bin:${PATH}"
COPY --from=feature-dockerfile-language-server --link "/opt/dockerfile-language-server/" "/opt/dockerfile-language-server/"
RUN \
    --mount=type=bind,source=./features/src/dockerfile-language-server/,target=/features/src/dockerfile-language-server/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/dockerfile-language-server/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/opt/editorconfig/node_modules:${NODE_PATH}"
ENV PATH="/opt/editorconfig/node_modules/.bin:${PATH}"
COPY --from=feature-editorconfig --link "/opt/editorconfig/" "/opt/editorconfig/"
RUN \
    --mount=type=bind,source=./features/src/editorconfig/,target=/features/src/editorconfig/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/editorconfig/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV PATH="/opt/markdown-oxide/bin:${PATH}"
COPY --from=feature-markdown-oxide --link "/opt/markdown-oxide/" "/opt/markdown-oxide/"
RUN \
    --mount=type=bind,source=./features/src/markdown-oxide/,target=/features/src/markdown-oxide/ \
    --mount=type=cache,target=/tmp/markdown-oxide/,sharing=locked \
    sh "/features/src/markdown-oxide/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV NODE_PATH="/opt/prettier/node_modules:${NODE_PATH}"
ENV PATH="/opt/prettier/node_modules/.bin:${PATH}"
COPY --from=feature-prettier --link "/opt/prettier/" "/opt/prettier/"
RUN \
    --mount=type=bind,source=./features/src/prettier/,target=/features/src/prettier/ \
    --mount=type=cache,target=/root/.npm/,sharing=locked \
    sh "/features/src/prettier/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV CARGO_HOME="/opt/rust/cargo/"
ENV PATH="/opt/rust/cargo/bin:${PATH}"
ENV RUSTUP_HOME="/opt/rust/rustup/"
COPY --from=feature-rust --link "/opt/rust/" "/opt/rust/"
RUN \
    --mount=type=bind,source=./features/src/rust/,target=/features/src/rust/ \
    --mount=type=cache,target=/tmp/rust/,sharing=locked \
    sh "/features/src/rust/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV PATH="/opt/shellcheck/bin:${PATH}"
COPY --from=feature-shellcheck --link "/opt/shellcheck/" "/opt/shellcheck/"
RUN \
    --mount=type=bind,source=./features/src/shellcheck/,target=/features/src/shellcheck/ \
    --mount=type=cache,target=/tmp/shellcheck/,sharing=locked \
    sh "/features/src/shellcheck/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV PATH="/opt/shfmt/bin:${PATH}"
COPY --from=feature-shfmt --link "/opt/shfmt/" "/opt/shfmt/"
RUN \
    --mount=type=bind,source=./features/src/shfmt/,target=/features/src/shfmt/ \
    --mount=type=cache,target=/tmp/shfmt/,sharing=locked \
    sh "/features/src/shfmt/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV PATH="/opt/taplo/bin:${PATH}"
COPY --from=feature-taplo --link "/opt/taplo/" "/opt/taplo/"
RUN \
    --mount=type=bind,source=./features/src/taplo/,target=/features/src/taplo/ \
    --mount=type=cache,target=/tmp/taplo/,sharing=locked \
    sh "/features/src/taplo/configure.sh"

# @see: [acquire.sh](https://github.com/devcontainers/spec/issues/21)
ENV PATH="/opt/zig/local/bin:/opt/zig/bin:${PATH}"
COPY --from=feature-zig --link "/opt/zig/" "/opt/zig/"
RUN \
    --mount=type=bind,source=./features/src/zig/,target=/features/src/zig/ \
    --mount=type=cache,target=/tmp/zig/,sharing=locked \
    sh "/features/src/zig/configure.sh"
